version: '3.3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  movies:
    build: ./movies
    image: go-simple-microservices-app/movies
    container_name: cinema-movies
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: movies.local

  bookings:
    build: ./bookings
    image: go-simple-microservices-app/bookings
    container_name: cinema-bookings
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: bookings.local

  showtimes:
    build: ./showtimes
    image: go-simple-microservices-app/showtimes
    container_name: cinema-showtimes
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: showtimes.local

  users:
    build: ./users
    image: go-simple-microservices-app/users
    container_name: cinema-users
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: users.local

  db:
    image: mongo:3.3
    container_name: cinema-db
    expose:
      - "27017"
    volumes:
      - ./backup:/backup:rw